version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: food-tracker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: food_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    # build: .
    image: psyduck130088/food-tracker-backend:latest
    container_name: food-tracker-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres123@postgres:5432/food_tracker
      - JWT_SECRET=your_super_secret_jwt_key_change_in_production
    depends_on:
      - postgres
    #volumes:
    #  - .:/app
    #  - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data:
